#!/bin/bash

set -e

HOME_DIR="${HOME}"
REPO_DIR=$(realpath ./openbmc)
MOUNT_DIRS=""
PASSTHROUGH_ADDITIONS=""

if [ -n "${DL_DIR}" ]; then
   MOUNT_DIRS="--volume $(readlink -f "${DL_DIR}"):${HOME_DIR}/downloads:rw --env DL_DIR=${HOME_DIR}/downloads"
   PASSTHROUGH_ADDITIONS="DL_DIR"
fi

if [ -n "${SSTATE_DIR}" ]; then
   MOUNT_DIRS="${MOUNT_DIRS} --volume $(readlink -f "${SSTATE_DIR}"):${HOME_DIR}/sstate:rw --env SSTATE_DIR=${HOME_DIR}/sstate"
   PASSTHROUGH_ADDITIONS="${PASSTHROUGH_ADDITIONS} SSTATE_DIR"
fi

docker run --volume ${REPO_DIR}:${HOME_DIR}/openbmc:rw --volume /tmp:/tmp \
  --workdir=${HOME_DIR}/openbmc \
  ${MOUNT_DIRS} \
  ${PASSTHROUGH_ADDITIONS:+--env BB_ENV_PASSTHROUGH_ADDITIONS="${PASSTHROUGH_ADDITIONS}"} \
  --env TERM=xterm-256color --env SHELL=/bin/bash \
  --rm --init --tty --interactive \
  --hostname dockerbmc \
  obmcbuilder
