#!/bin/sh

set -e

HOME_DIR="/home/builder"
REPO_DIR=`realpath ./openbmc`
MOUNT_DLDIR=""
EXTRA_BB_ENV_VARS=""

if [ -n "${DL_DIR}" ]; then
   MOUNT_DLDIR="-v $(readlink -f "${DL_DIR}"):${HOME_DIR}/downloads:rw -e DL_DIR=${HOME_DIR}/downloads"
fi

#if [ -n "${BB_ENV_EXTRAWHITE}" ]; then
#   EXTRA_BB_ENV_VARS="-e BB_ENV_EXTRAWHITE="${BB_ENV_EXTRAWHITE}""
#BB_ENV_EXTRAWHITE="ALL_PROXY BBPATH_EXTRA BB_LOGCONFIG BB_NO_NETWORK BB_NUMBER_THREADS BB_SETSCENE_ENFORCE BB_SRCREV_POLICY DISTRO FTPS_PROXY FTP_PROXY GIT_PROXY_COMMAND HTTPS_PROXY HTTP_PROXY MACHINE NO_PROXY PARALLEL_MAKE SCREENDIR SDKMACHINE SOCKS5_PASSWD SOCKS5_USER SSH_AGENT_PID SSH_AUTH_SOCK STAMPS_DIR TCLIBC TCMODE all_proxy ftp_proxy ftps_proxy http_proxy https_proxy no_proxy  SSTATE_DIR DL_DIR TMPDIR"
#fi

docker run -v ${REPO_DIR}:${HOME_DIR}/openbmc:rw --workdir=${HOME_DIR}/openbmc \
  ${MOUNT_DLDIR} -e BB_ENV_EXTRAWHITE='DL_DIR BB_NUMBER_THREADS' -e BB_NUMBER_THREADS=6 \
  -e USER_ID=1000 -e GROUP_ID=1000 -e TERM=xterm-256color -e SHELL=/bin/bash \
  --rm --init -t -i \
  --hostname dockerbmc \
  obmcbuilder bash
